-- DROP EXISTING TABLES AND TYPES TO START FRESH
DROP TABLE IF EXISTS admin_logs CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TYPE IF EXISTS order_status CASCADE;

-- Create Enum for Order Status
CREATE TYPE order_status AS ENUM ('Pending', 'Processing', 'Shipped', 'Completed', 'Cancelled');

-- Create Customers Table
CREATE TABLE customers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Addresses Table
CREATE TABLE addresses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
  address_line TEXT,
  subdistrict TEXT,
  district TEXT,
  province TEXT,
  zipcode TEXT,
  full_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Products Table (สำหรับสินค้าระบบใหม่ แทนที่ไฟล์ products.js)
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ใช้ BIGINT ให้ตรงกับเลข id เดิม
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  stock_quantity INTEGER DEFAULT 0,
  image TEXT,
  images TEXT[] DEFAULT '{}',
  specs JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Orders Table
CREATE TABLE orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  order_no TEXT UNIQUE NOT NULL, -- เช่น ORD-123456
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  address_id UUID REFERENCES addresses(id) ON DELETE SET NULL,
  status order_status DEFAULT 'Pending',
  subtotal DECIMAL(10, 2) NOT NULL DEFAULT 0,
  shipping DECIMAL(10, 2) NOT NULL DEFAULT 0,
  total DECIMAL(10, 2) NOT NULL DEFAULT 0,
  admin_note TEXT,
  tracking_no TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Order Items Table
-- ไม่ได้บังคับ reference ไปยัง products(id) เสมอ เผื่อมีสินค้าที่โดนลบ ทิ้งไว้เป็น TEXT ได้
CREATE TABLE order_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  product_id TEXT, -- ปล่อยเป็น TEXT เพื่อความยืดหยุ่นในกรณีรหัสสินค้าจากระบบเก่า
  product_name TEXT NOT NULL,
  product_image TEXT,
  unit_price DECIMAL(10, 2) NOT NULL,
  quantity INTEGER NOT NULL,
  line_total DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Payments Table
CREATE TABLE payments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  method TEXT NOT NULL, -- เช่น 'promptpay', 'cod', 'credit_card'
  status TEXT DEFAULT 'pending', -- เช่น 'pending', 'paid', 'failed', 'refunded'
  reference_no TEXT,
  payload JSONB, -- เก็บ raw data ของบิล/สลิปเผื่อแอดมินดูย้อนหลัง
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Admin Activity Log Table (ตารางพิเศษสำหรับเก็บประวัติแอดมิน เพื่อความโปร่งใส)
CREATE TABLE admin_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  action TEXT NOT NULL, -- เช่น 'UPDATE_ORDER', 'DELETE_PRODUCT'
  entity_type TEXT NOT NULL, -- เช่น 'Order', 'Product'
  entity_id TEXT NOT NULL,
  details JSONB, -- เล่าว่าเปลี่ยนอะไรไปบ้าง
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- +-------------------------------------------------------------------+
-- | TRIGGERS: ทำให้คอลัมน์ updated_at อัพเดตตัวเองอัตโนมัติเมื่อแก้ข้อมูล |
-- +-------------------------------------------------------------------+
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_customers_updated_at BEFORE UPDATE ON customers FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_addresses_updated_at BEFORE UPDATE ON addresses FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- +-------------------------------------------------------------------+
-- | RLS (Row Level Security): เบื้องต้นตั้งค่าให้อ่านเขียนได้ง่ายๆ ก่อน      |
-- | (ค่อยไปจำกัดสิทธิ์ในอนาคต หากต้องการระบบที่ปลอดภัยแน่นหนาขึ้น)           |
-- +-------------------------------------------------------------------+
-- รันชุดนี้ถ้าต้องการให้เข้าถึง API ผ่าน anon key ได้ (เหมาะกับช่วงพัฒนา)
/*
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for development" ON customers FOR ALL USING (true);
CREATE POLICY "Enable all for development" ON addresses FOR ALL USING (true);
CREATE POLICY "Enable all for development" ON products FOR ALL USING (true);
CREATE POLICY "Enable all for development" ON orders FOR ALL USING (true);
CREATE POLICY "Enable all for development" ON order_items FOR ALL USING (true);
CREATE POLICY "Enable all for development" ON payments FOR ALL USING (true);
*/

-- Create Product Reviews Table (สำหรับเก็บรีวิวสินค้า)
CREATE TABLE product_reviews (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  product_id TEXT, -- ปล่อยเป็น TEXT เพื่อความยืดหยุ่นถ้าสินค้าถูกลบ
  product_name TEXT,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
