import pg from 'pg';
import { products } from './src/data/products.js';
import dotenv from 'dotenv';

// Load environment variables from .env file
dotenv.config();

const { Client } = pg;
const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  console.error('❌ Error: DATABASE_URL is missing in your .env file.');
  console.error('Please add DATABASE_URL=postgresql://[user]:[password]@[host]/[dbname]?sslmode=require');
  process.exit(1);
}

const client = new Client({
  connectionString,
  ssl: {
    rejectUnauthorized: false
  }
});

async function runSeed() {
  console.log('🌱 Connecting to Neon PostgreSQL...');
  await client.connect();
  console.log('✅ Connected successfully!');

  try {
    console.log('🧹 Cleaning existing tables and types...');
    await client.query('DROP TABLE IF EXISTS product_reviews CASCADE;');
    await client.query('DROP TABLE IF EXISTS admin_logs CASCADE;');
    await client.query('DROP TABLE IF EXISTS payments CASCADE;');
    await client.query('DROP TABLE IF EXISTS order_items CASCADE;');
    await client.query('DROP TABLE IF EXISTS orders CASCADE;');
    await client.query('DROP TABLE IF EXISTS products CASCADE;');
    await client.query('DROP TABLE IF EXISTS addresses CASCADE;');
    await client.query('DROP TABLE IF EXISTS customers CASCADE;');
    await client.query('DROP TYPE IF EXISTS order_status CASCADE;');

    console.log('🛠️ Creating database types...');
    await client.query(`
      CREATE TYPE order_status AS ENUM ('Pending', 'Processing', 'Shipped', 'Completed', 'Cancelled');
    `);

    console.log('🛠️ Creating tables...');
    
    // Customers
    await client.query(`
      CREATE TABLE customers (
        id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
        full_name TEXT NOT NULL,
        email TEXT,
        phone TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Addresses
    await client.query(`
      CREATE TABLE addresses (
        id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
        customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
        address_line TEXT,
        subdistrict TEXT,
        district TEXT,
        province TEXT,
        zipcode TEXT,
        full_address TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Products
    await client.query(`
      CREATE TABLE products (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        description TEXT,
        price DECIMAL(10, 2) NOT NULL,
        stock_quantity INTEGER DEFAULT 0,
        image TEXT,
        images TEXT[] DEFAULT '{}',
        specs JSONB DEFAULT '[]'::jsonb,
        is_active BOOLEAN DEFAULT true,
        ingredients TEXT,
        origin TEXT,
        mfg_date TEXT,
        exp_date TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Orders
    await client.query(`
      CREATE TABLE orders (
        id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
        order_no TEXT UNIQUE NOT NULL,
        customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
        address_id UUID REFERENCES addresses(id) ON DELETE SET NULL,
        status order_status DEFAULT 'Pending',
        subtotal DECIMAL(10, 2) NOT NULL DEFAULT 0,
        shipping DECIMAL(10, 2) NOT NULL DEFAULT 0,
        total DECIMAL(10, 2) NOT NULL DEFAULT 0,
        admin_note TEXT,
        tracking_no TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Order Items
    await client.query(`
      CREATE TABLE order_items (
        id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
        order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
        product_id TEXT,
        product_name TEXT NOT NULL,
        product_image TEXT,
        unit_price DECIMAL(10, 2) NOT NULL,
        quantity INTEGER NOT NULL,
        line_total DECIMAL(10, 2) NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Payments
    await client.query(`
      CREATE TABLE payments (
        id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
        order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
        method TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        reference_no TEXT,
        payload JSONB,
        paid_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // Product Reviews
    await client.query(`
      CREATE TABLE product_reviews (
        id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
        order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
        product_id TEXT,
        product_name TEXT,
        rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
        comment TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    console.log('🎉 Database Schema built successfully!');

    console.log('🌱 Starting to seed products...');
    for (const product of products) {
      console.log(`Inserting: ${product.name}`);
      await client.query(
        `INSERT INTO products (id, name, category, description, price, specs, image, is_active, ingredients, origin, mfg_date, exp_date)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
        [
          product.id,
          product.name,
          product.category,
          product.description,
          product.price,
          JSON.stringify(product.specs),
          product.image,
          true,
          product.ingredients || 'ส่วนประกอบสำคัญทางยา (Active Ingredients)',
          product.origin || 'ประเทศไทย (Thailand)',
          product.mfg_date || '2026-01-15',
          product.exp_date || '2029-01-15'
        ]
      );
    }
    console.log('🎉 Seeding products completed successfully!');

  } catch (error) {
    console.error('❌ Error during database seeding:', error.message);
  } finally {
    await client.end();
    console.log('🔌 Disconnected from Neon PostgreSQL.');
  }
}

runSeed();
